server:
  port: 8083

spring:
  application:
    name: RatingService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-ratingservice
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka